# Generated by Django 4.2.16 on 2024-10-20 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetkpi",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_kpis",
                to="kpi.kpi",
            ),
        ),
        migrations.AlterField(
            model_name="kpi",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
