# Generated by Django 5.1.2 on 2024-12-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_alter_assetkpi_kpi_alter_kpi_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=255)),
                ('attribute_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('interval', models.CharField(max_length=255)),
                ('kpi_id', models.CharField(max_length=255)),
            ],
        ),
    ]
