# Generated by Django 5.1.2 on 2024-12-17 10:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_assetattribute_simulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetkpi',
            name='asset_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
