# Generated by Django 5.1.2 on 2024-12-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_assetkpi_asset_value_alter_assetkpi_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_value',
            field=models.CharField(max_length=10),
        ),
    ]
