# Generated by Django 5.1.4 on 2024-12-17 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0006_alter_assetkpi_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='kpi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_id', to='kpi.kpi'),
        ),
    ]
