# Generated by Django 5.1.2 on 2025-01-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assetattribute_assetkpi_kpi_simulator_delete_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssetAttribute',
        ),
    ]
