# Generated by Django 5.1.2 on 2024-12-17 10:50

import kpi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0005_alter_assetkpi_asset_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetkpi',
            name='asset_id',
            field=models.CharField(default=kpi.models.generate_unique_asset_id, max_length=255, unique=True),
        ),
    ]
