# Generated by Django 5.1.4 on 2024-12-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_alter_assetkpi_asset_id_alter_simulator_kpi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='kpi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi'),
        ),
    ]
